const BD_DISTRICTS = {
  "Bagerhat": { en: "Bagerhat", bn: "বাগেরহাট" },
  "Bandarban": { en: "Bandarban", bn: "বান্দরবান" },
  "Barguna": { en: "Barguna", bn: "বরগুনা" },
  "Barisal": { en: "Barishal", bn: "বরিশাল" },
  "Bhola": { en: "Bhola", bn: "ভোলা" },
  "Bogra": { en: "Bogura", bn: "বগুড়া" },
  "Brahamanbaria": { en: "Brahmanbaria", bn: "ব্রাহ্মণবাড়িয়া" },
  "Chandpur": { en: "Chandpur", bn: "চাঁদপুর" },
  "Chittagong": { en: "Chattogram", bn: "চট্টগ্রাম" },
  "Chuadanga": { en: "Chuadanga", bn: "চুয়াডাঙ্গা" },
  "Comilla": { en: "Cumilla", bn: "কুমিল্লা" },
  "Cox's Bazar": { en: "Cox's Bazar", bn: "কক্সবাজার" },
  "Dhaka": { en: "Dhaka", bn: "ঢাকা" },
  "Dinajpur": { en: "Dinajpur", bn: "দেবগ্রাম" },
  "Faridpur": { en: "Faridpur", bn: "ফরিদপুর" },
  "Feni": { en: "Feni", bn: "ফেনী" },
  "Gaibandha": { en: "Gaibandha", bn: "গাইবান্ধা" },
  "Gazipur": { en: "Gazipur", bn: "গাজীপুর" },
  "Gopalganj": { en: "Gopalganj", bn: "গোপালগঞ্জ" },
  "Habiganj": { en: "Habiganj", bn: "হবিগঞ্জ" },
  "Jamalpur": { en: "Jamalpur", bn: "জামালপুর" },
  "Jessore": { en: "Jashore", bn: "যশোর" },
  "Jhalokati": { en: "Jhalakati", bn: "ঝালকাঠী" },
  "Jhenaidah": { en: "Jhenaidah", bn: "ঝিনাইদহ" },
  "Joypurhat": { en: "Joypurhat", bn: "জয়পুরহাট" },
  "Khagrachhari": { en: "Khagrachari", bn: "খাগড়াছড়ি" },
  "Khulna": { en: "Khulna", bn: "খুলনা" },
  "Kishoreganj": { en: "Kishoreganj", bn: "কিশোরগঞ্জ" },
  "Kurigram": { en: "Kurigram", bn: "কুড়িগ্রাম" },
  "Kushtia": { en: "Kushtia", bn: "কুষ্টিয়া" },
  "Lakshmipur": { en: "Lakshmipur", bn: "লক্ষ্মীপুর" },
  "Lalmonirhat": { en: "Lalmonirhat", bn: "লালমনিরহাট" },
  "Madaripur": { en: "Madaripur", bn: "মাদারীপুর" },
  "Magura": { en: "Magura", bn: "মাগুরা" },
  "Manikganj": { en: "Manikganj", bn: "মানিকগঞ্জ" },
  "Maulvibazar": { en: "Maulvibazar", bn: "মৌলভীবাজার" },
  "Meherpur": { en: "Meherpur", bn: "মেহেরপুর" },
  "Munshiganj": { en: "Munshiganj", bn: "মুন্সিগঞ্জ" },
  "Mymensingh": { en: "Mymensingh", bn: "ময়মনসিংহ" },
  "Naogaon": { en: "Naogaon", bn: "নওগাঁ" },
  "Narail": { en: "Narail", bn: "নারায়ণগঞ্জ" },
  "Narayanganj": { en: "Narayanganj", bn: "নারায়ণগঞ্জ" },
  "Narsingdi": { en: "Narsingdi", bn: "নরসিংদী" },
  "Natore": { en: "Natore", bn: "নটোর" },
  "Nawabganj": { en: "Nawabganj", bn: "নবাবগঞ্জ" },
  "Netrakona": { en: "Netrokona", bn: "নেত্রকোনা" },
  "Nilphamari": { en: "Nilphamari", bn: "নীলফামারী" },
  "Noakhali": { en: "Noakhali", bn: "নোয়াখালী" },
  "Pabna": { en: "Pabna", bn: "পাবনা" },
  "Panchagarh": { en: "Panchagarh", bn: "পঞ্চগড়" },
  "Patuakhali": { en: "Patuakhali", bn: "পটুখালী" },
  "Pirojpur": { en: "Pirojpur", bn: "পিরোজপুর" },
  "Rajbari": { en: "Rajbari", bn: "রাজবাড়ী" },
  "Rajshahi": { en: "Rajshahi", bn: "রাজশাহী" },
  "Rangamati": { en: "Rangamati", bn: "রাঙ্গামাটি" },
  "Rangpur": { en: "Rangpur", bn: "রংপুর" },
  "Satkhira": { en: "Satkhira", bn: "সাতক্ষীরা" },
  "Shariatpur": { en: "Shariatpur", bn: "শরীয়তপুর" },
  "Sherpur": { en: "Sherpur", bn: "শেরপুর" },
  "Sirajganj": { en: "Sirajganj", bn: "সিরাজগঞ্জ" },
  "Sunamganj": { en: "Sunamganj", bn: "সুনামগঞ্জ" },
  "Sylhet": { en: "Sylhet", bn: "সিলেট" },
  "Tangail": { en: "Tangail", bn: "টাঙ্গাইল" },
  "Thakurgaon": { en: "Thakurgaon", bn: "ঠাকুরগাঁও" }
};

const ALPHA3_TO_ALPHA2 = {
  "AFG":"AF","AGO":"AO","ALB":"AL","DZA":"DZ","ASM":"AD","AND":"AI","ARE":"AE","ARG":"AR",
  "ARM":"AM","ABW":"AW","AUS":"AU","AUT":"AT","AZE":"AZ","BHS":"BS","BHR":"BH","BGD":"BD",
  "BEL":"BE","BEN":"BJ","BMU":"BM","BGR":"BG","BFA":"BF","BDI":"BI","BLM":"BL","BLR":"BY",
  "BLZ":"BZ","CAN":"CA","CYM":"KY","CAF":"CF","COG":"CG","CHE":"CH","CHL":"CL","CIV":"CI",
  "CHN":"CN","CMR":"CM","CPV":"CV","CUB":"CU","CUW":"CW","CRI":"CR","CYP":"CY","CZE":"CZ",
  "COD":"CD","COK":"CK","HRV":"HR","HAI":"HT","HUN":"HU","IDN":"ID","IRL":"IE","ISR":"IL",
  "IND":"IN","IRQ":"IQ","IRN":"IR","ISL":"IS","ITA":"IT","JAM":"JM","JOR":"JO","JPN":"JP",
  "KAZ":"KZ","KEN":"KE","KHM":"KH","KIR":"KG","KWT":"KW","LAO":"LA","LBN":"LB","LBR":"LR",
  "LSO":"LS","LIE":"LI","LKA":"LK","LTU":"LT","LUX":"LU","LVA":"LV","MAC":"MO","MDG":"MG",
  "MDV":"MV","MEX":"MX","MKD":"MK","MLI":"ML","MLT":"MT","MHL":"MH","MAR":"MA","MMR":"MM",
  "MNE":"ME","MRT":"MR","MNG":"MN","MSR":"MU","MDA":"MD","MCO":"MC","MWI":"MW","MYS":"MY",
  "NAM":"NA","NRU":"NR","NPL":"NP","NLD":"NL","NIC":"NI","NGA":"NG","NOR":"NO","NCL":"NC",
  "NZL":"NZ","OMN":"OM","PAK":"PK","PAN":"PA","PNG":"PG","PRK":"KP","PER":"PE","PHL":"PH",
  "PLW":"PW","POL":"PL","PRT":"PT","PRI":"PR","QAT":"QA","ROU":"RO","RUS":"RU","RWA":"RW",
  "SGP":"SG","SVK":"SK","SVN":"SI","SYC":"SC","SDN":"SD","SRB":"RS","SLB":"SB","SWE":"SE",
  "TWN":"TW","TJK":"TJ","TZA":"TZ","THA":"TH","TGO":"TG","TLS":"TL","TON":"TO","TTO":"TT",
  "TUN":"TN","TUR":"TR","TKM":"TM","TUV":"TV","UGA":"UG","UKR":"UA","URY":"UY","USA":"US",
  "UZB":"UZ","VEN":"VE","VNM":"VN","VUT":"VU","WSM":"WS","YEM":"YE","ZAF":"ZA","ZMB":"ZM",
  "ZWE":"ZW","ESH":"EH","GGY":"GG","IMN":"IM","JEY":"JE","ATA":"AQ","BVT":"BV","FLK":"FK",
  "GIB":"GI","GLP":"GP","GRD":"GD","GUM":"GU","HMD":"HM","IOT":"IO","KNA":"KN","LCA":"LC",
  "MAF":"MF","MAQ":"MQ","MTQ":"MT","NFK":"NF","PYF":"PF","PCN":"PN","REU":"RE","SXM":"SX",
  "TCA":"TC","VGB":"VG","VIR":"VI","WLF":"WF","MYT":"YT","ANT":"AN","BUR":"BU","NTZ":"DZ",
  "GEI":"GE","FMI":"MI","SCG":"CS","SRG":"RS","SRF":"CS","URS":"UU","YUG":"YU","ZAR":"ZA",
  "BSH":"BH","CSK":"CS","DDR":"DD","FRG":"DE","KOR":"KR","MUS":"MU","NMI":"FM","SAH":"EH",
  "SEN":"SN","SHN":"SH","SIN":"SG","SOM":"SO","SPM":"PM","SUR":"SR","SWZ":"SZ","TCD":"TD",
  "TMP":"TP","UAW":"UZ","UML":"UM","UMY":"UM","VCT":"VC","VGQ":"GP","ZIM":"ZW"
};

function flagEmoji(alpha2) {
  if (!alpha2 || alpha2.length !== 2) return "🌍";
  return alpha2.toUpperCase().split("").map(c => String.fromCodePoint(127397 + c.charCodeAt(0))).join("");
}

function flagFromAlpha3(alpha3) {
  const a2 = ALPHA3_TO_ALPHA2[(alpha3 || "").toUpperCase()];
  return flagEmoji(a2 || "");
}
